name: MLproject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  
  - pandas
  - scikit-learn
  - pyyaml
  - ipykernel
  - pytest
  - mlflow
  - dvc 
  - setuptools
  - pip 
  - pip:
    - dvc-gdrive