data:
  raw_path: "data/raw/salary_data.csv"
  processed_path: "data/processed/salary_cleaned.csv"
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 10  # <--- Run dvc repro, change value, Run dvc repro again, compare models
  max_depth: 3
  experiment_name: "salary_prediction"