data:
  raw_path: "data/raw/dataset.csv"
  processed_path: "data/processed/clean_data.csv"
  test_size: 0.2
  random_state: 42

train:
  experiment_name: "Default_Experiment"
  model_type: "RandomForest"
  n_estimators: 100
  max_depth: 10